name: langs

on: push

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run golang
        run: cd golang && go run .
      - name: Run golnag
        run: go version
