name: langs

on: push

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Golang version
        run: go version
      - uses: actions/checkout@v4
      - name: Run Golang
        run: cd golang && go run .
